---
title: "Systematic Search"
author: "Emma Wilson"
date: "29/03/2021"
output: 
  html_notebook:
    theme: cosmo
---
# Load libraries

```{r set-up}
library(readr)                   # read and write files
library(readxl)                  # read Excel files
library(pubmedTools)             # automatic PubMed search retrieval
library(dplyr)                   # data transformation
library(stringr)                 # manipulate strings
library(data.table)              # read multiple files in loop
library(purrr)                   # read multiple files in loop
source("functions/searchPubMed.R") # automatic search of PubMed using PubMedTools
source("functions/readEmbase.R")   # reads Embae files in a loop
source("functions/formatEmbase.R") # formats Embase data to merge with PubMed
dir.create("search-updates")     # Create directory for search update files if doesn't already exist
```

# Set search dates

```{r set-date}
searchDate <- paste0(Sys.Date()) # date current search is performed
lastSearchDate <- "" # date of last search
#create directory folders
searchfolder <- paste0("search-updates/", searchDate)
dir.create(searchfolder)
```

# Run systematic searches

## PubMed search

```{r search-pubmed}
# Automatic PubMed search
pubmed <- searchPubMed(searchDate, lastSearchDate)
# Write csv file of citations retrieved from PubMed search
write_csv(pubmed, paste0(searchfolder, "/pubmed.csv"))
```

## Embase search

```{r}
# Read in and format Embase search results
embase <- readEmbase(searchfolder, "*.xlsx")
```

# Merge and write search file

```{r}
# Remove PMID column
embase_noPMID <- select(embase, -PMID)
# Merge together
search_all <- rbind(pubmed, embase_noPMID)
# Write csv file
write_csv(search_all, paste0(searchfolder, "/search.csv"))
```
